# Generated by Django 3.0.3 on 2020-03-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
