# Generated by Django 3.0.3 on 2020-03-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0005_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='suscripcion',
        ),
    ]
