# Generated by Django 3.0.3 on 2020-03-16 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0006_remove_cliente_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ejemplo.cliente'),
            preserve_default=False,
        ),
    ]
