# Generated by Django 3.0.3 on 2020-03-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0007_suscripcion_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.DeleteModel(
            name='suscripcion',
        ),
    ]
