# Generated by Django 3.0.3 on 2020-03-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0008_auto_20200321_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipocliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
