# Generated by Django 3.0.3 on 2020-03-22 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0009_tipocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('patente', models.CharField(max_length=60)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ejemplo.tipocliente')),
            ],
        ),
    ]
