# Generated by Django 3.0.3 on 2020-03-22 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0010_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
