# Generated by Django 3.0.3 on 2020-03-22 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0012_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('estado', models.CharField(max_length=40)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ejemplo.cliente')),
            ],
        ),
    ]
