# Generated by Django 3.0.3 on 2020-03-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0013_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='pruebas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('estado', models.CharField(default='vigente', max_length=40)),
            ],
        ),
    ]
