# Generated by Django 3.0.3 on 2020-03-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0015_delete_pruebas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(default='vigente', max_length=40),
        ),
    ]
