# Generated by Django 3.0.3 on 2020-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0016_auto_20200322_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='repuestos',
            fields=[
                ('cod_repuesto', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=400)),
                ('descripcion', models.TextField(max_length=400)),
                ('no_parte', models.IntegerField()),
                ('precio_Compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock', models.PositiveSmallIntegerField()),
                ('isr', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
            ],
        ),
    ]
