# Generated by Django 3.0.3 on 2020-03-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0017_repuestos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='repuestos',
            new_name='repuesto',
        ),
    ]
