# Generated by Django 3.0.3 on 2020-03-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0018_auto_20200323_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='cod_repuesto',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
