# Generated by Django 3.0.3 on 2020-03-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0023_repuesto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='repuesto',
        ),
    ]
