# Generated by Django 3.0.3 on 2020-03-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0024_delete_repuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='fabrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
    ]
