# Generated by Django 3.0.3 on 2020-03-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0026_repuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('linea', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
