# Generated by Django 3.0.3 on 2020-03-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0030_detallefactura_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
