# Generated by Django 3.0.3 on 2020-03-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0031_repuesto_igv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='tipopago',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='vendedor',
        ),
    ]
