# Generated by Django 3.0.3 on 2020-04-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0032_auto_20200330_0026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
    ]
