# Generated by Django 3.0.3 on 2020-04-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0033_delete_detallefactura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
