# Generated by Django 3.0.3 on 2020-04-04 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0035_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cantidad', models.IntegerField()),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fabrica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ejemplo.fabrica')),
                ('orden', models.ForeignKey(db_column='orden_id', on_delete=django.db.models.deletion.PROTECT, related_name='orden', to='ejemplo.Orden')),
                ('producto', models.ForeignKey(db_column='repuesto_id', on_delete=django.db.models.deletion.PROTECT, to='ejemplo.repuesto')),
            ],
        ),
    ]
