# Generated by Django 3.0.3 on 2020-04-04 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0036_detalleorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.IntegerField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ejemplo.Orden')),
            ],
        ),
    ]
