# Generated by Django 3.0.3 on 2020-04-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0040_auto_20200404_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
    ]
