# Generated by Django 3.0.3 on 2020-04-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0041_remove_factura_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
