# Generated by Django 3.0.3 on 2020-04-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0045_remove_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
