# Generated by Django 3.0.3 on 2020-04-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0046_factura_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.CharField(max_length=101),
        ),
    ]
