# Generated by Django 3.0.3 on 2020-04-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0047_auto_20200404_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.CharField(max_length=101),
        ),
    ]
