# Generated by Django 3.0.3 on 2020-04-05 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0048_auto_20200404_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(db_column='repuesto_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='ejemplo.repuesto'),
            preserve_default=False,
        ),
    ]
