# Generated by Django 3.0.3 on 2020-04-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0049_detallefactura_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
    ]
