# Generated by Django 3.0.3 on 2020-04-05 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0050_delete_detallefactura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
