# Generated by Django 3.0.3 on 2020-04-05 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0052_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cantidad', models.IntegerField()),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('detalleorden', models.ForeignKey(db_column='detalleorden_id', on_delete=django.db.models.deletion.PROTECT, related_name='detalleorden', to='ejemplo.DetalleOrden')),
                ('fabrica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ejemplo.fabrica')),
                ('factura', models.ForeignKey(db_column='factura_id', on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='ejemplo.Factura')),
                ('producto', models.ForeignKey(db_column='repuesto_id', on_delete=django.db.models.deletion.PROTECT, to='ejemplo.repuesto')),
            ],
        ),
    ]
