# Generated by Django 3.0.3 on 2020-04-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0053_detallefactura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='client',
            new_name='cliente',
        ),
    ]
