# Generated by Django 3.0.3 on 2020-04-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0054_auto_20200404_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoRecibido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('cantidad', models.CharField(max_length=40)),
            ],
        ),
    ]
