# Generated by Django 3.0.3 on 2020-05-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0055_pedidorecibido'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
