# Generated by Django 3.0.3 on 2020-05-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0056_repuesto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='imagen2',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
